package poo.pl2.views;

import javax.swing.JOptionPane;
import poo.pl2.models.SignIn_m;

/**
 *
 * @author pablo
 */
public class TarjetaCredito_v extends javax.swing.JDialog {

    /**
     * Creates new form TarjetaCredito_v
     * @param parent
     * @param modal
     */
    public TarjetaCredito_v(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        TextPrompt numeroTarjetaa = new TextPrompt("Número tarjeta", numeroTarjeta);
        TextPrompt titularr = new TextPrompt("Titular de la tarjeta", titular);
        TextPrompt fechaNacimientoo = new TextPrompt("DD/MM/YYYY", fechaNacimiento);
        
        getContentPane().setBackground(new java.awt.Color(50, 55, 55));
        
        this.setTitle("Tarjeta de Crédito | JavaEat");
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titular1 = new javax.swing.JTextField();
        titular2 = new javax.swing.JTextField();
        numeroTarjeta = new javax.swing.JTextField();
        titular = new javax.swing.JTextField();
        fechaNacimiento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        titular1.setText("jTextField1");

        titular2.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        numeroTarjeta.setBackground(java.awt.Color.darkGray);
        numeroTarjeta.setForeground(new java.awt.Color(200, 200, 200));
        numeroTarjeta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        numeroTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numeroTarjetaKeyTyped(evt);
            }
        });

        titular.setBackground(java.awt.Color.darkGray);
        titular.setForeground(new java.awt.Color(200, 200, 200));
        titular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                titularKeyTyped(evt);
            }
        });

        fechaNacimiento.setBackground(java.awt.Color.darkGray);
        fechaNacimiento.setForeground(new java.awt.Color(200, 200, 200));
        fechaNacimiento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fechaNacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechaNacimientoKeyTyped(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.darkGray);
        jButton1.setForeground(new java.awt.Color(200, 200, 200));
        jButton1.setText("Introducir");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numeroTarjeta)
                    .addComponent(titular)
                    .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(numeroTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titular, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SignIn_m.registerTarjeta();
        JOptionPane.showMessageDialog(this, "Tarjeta de crédito registrada correctamente.");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void numeroTarjetaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numeroTarjetaKeyTyped
        // TODO add your handling code here:
        
        int key = evt.getKeyChar();
        
        boolean numero = key >= 48 && key <= 57;
        
        if (!numero) {
            
            evt.consume();
            
        }
    }//GEN-LAST:event_numeroTarjetaKeyTyped

    private void titularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titularKeyTyped
        // TODO add your handling code here:
        
        int key = evt.getKeyChar();
        
        boolean numero = key >= 65 && key <= 90 || key >= 97 && key <= 122 ;
        
        if (!numero) {
            
            evt.consume();
            
        }
    }//GEN-LAST:event_titularKeyTyped

    private void fechaNacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaNacimientoKeyTyped
        // TODO add your handling code here:
        
        int key = evt.getKeyChar();
        
        boolean numero = key >= 48 && key <= 57;
        
        if (!numero) {
            
            evt.consume();
            
        }
    }//GEN-LAST:event_fechaNacimientoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TarjetaCredito_v.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TarjetaCredito_v.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TarjetaCredito_v.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TarjetaCredito_v.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TarjetaCredito_v dialog = new TarjetaCredito_v(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField fechaNacimiento;
    private javax.swing.JButton jButton1;
    public static javax.swing.JTextField numeroTarjeta;
    public static javax.swing.JTextField titular;
    private javax.swing.JTextField titular1;
    private javax.swing.JTextField titular2;
    // End of variables declaration//GEN-END:variables
}
